"""
ai.provider — the swappable LLM provider abstraction (Layer 1).

The rest of the platform depends only on the :class:`LLMProvider` interface and
never on a concrete implementation. This is the single seam through which a real
model (Gemini, Claude, OpenAI, or a local LLM) can be plugged in later **without
touching the endpoints, the learner-context service, or the frontend**.

How to add a real provider later
--------------------------------
1. Subclass :class:`LLMProvider` (e.g. ``class ClaudeProvider(LLMProvider): ...``)
   and implement :meth:`LLMProvider.complete`.
2. Register it in :data:`_PROVIDER_REGISTRY` under a short key
   (e.g. ``"claude"``).
3. Set the environment variable ``AI_PROVIDER=claude`` (and whatever API key that
   provider reads from the environment).

Nothing else changes. ``get_provider()`` is the only place the process decides
which implementation to use, and it is cached so a provider is constructed once.

Why an "offline" default?
-------------------------
ByteForge is designed to run on free hosting tiers with a stdlib-only algorithm
engine and no secrets. :class:`OfflineProvider` gives deterministic, useful,
rule-based responses so every AI feature is demonstrable with no API key and no
network — while presenting the *exact same interface* a hosted LLM would.
"""

from __future__ import annotations

import os
import re
from abc import ABC, abstractmethod
from collections import Counter
from dataclasses import dataclass, field
from functools import lru_cache
from typing import Dict, List, Optional, Type


# ---------------------------------------------------------------------------
# Data contracts
# ---------------------------------------------------------------------------

@dataclass
class LLMMessage:
    """A single chat message in the neutral, provider-independent format.

    Concrete providers translate this into their own wire format (Anthropic's
    ``messages``, OpenAI's ``chat.completions``, Gemini's ``contents``, etc.).
    """

    role: str  # "system" | "user" | "assistant"
    content: str


@dataclass
class LLMResponse:
    """The normalized result returned by every provider.

    Keeping this uniform means callers (endpoints, future layers) never branch
    on which provider produced the answer.
    """

    text: str
    provider: str
    model: str
    # True when the response was produced by a real model call; False when it was
    # generated by the offline rule engine. The frontend can surface this so a
    # learner knows whether they are talking to a live model.
    is_live: bool = False
    # Free-form provider diagnostics (token counts, latency, fallback reason...).
    meta: Dict[str, object] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# The interface every provider must implement
# ---------------------------------------------------------------------------

class LLMProvider(ABC):
    """Abstract base class for all AI providers.

    A provider is a thin adapter around "given some messages, return text".
    Everything the platform needs from an LLM is expressed through this one
    method, which keeps the surface area small enough that a new backend is a
    self-contained addition.
    """

    #: Short, stable identifier used in :data:`_PROVIDER_REGISTRY` and returned
    #: to clients in :attr:`LLMResponse.provider`.
    name: str = "base"

    @abstractmethod
    def complete(
        self,
        messages: List[LLMMessage],
        *,
        max_tokens: int = 512,
        temperature: float = 0.4,
    ) -> LLMResponse:
        """Produce a completion for ``messages``.

        Parameters
        ----------
        messages:
            Ordered conversation, typically a ``system`` message followed by a
            ``user`` message.
        max_tokens:
            Upper bound on the length of the generated answer.
        temperature:
            Sampling temperature hint (ignored by the offline provider).

        Returns
        -------
        LLMResponse
            The normalized response. Implementations must **never raise for an
            empty answer** — return a best-effort :class:`LLMResponse` instead so
            the endpoints degrade gracefully.
        """
        raise NotImplementedError

    def is_available(self) -> bool:
        """Whether this provider is ready to serve live requests.

        The offline provider is always available. A hosted provider should return
        ``False`` when its API key is missing so :func:`get_provider` can fall
        back instead of crashing at request time.
        """
        return True


# ---------------------------------------------------------------------------
# The default, dependency-free provider
# ---------------------------------------------------------------------------

class OfflineProvider(LLMProvider):
    """A deterministic, rule-based provider that needs no network or API key.

    It is intentionally *not* a language model. Instead it inspects the incoming
    prompt for the structured markers the platform uses (see :mod:`ai.prompts`)
    and returns templated, pedagogically-useful text. This keeps every AI feature
    fully functional offline while conforming to the :class:`LLMProvider`
    contract, so replacing it with a real model changes nothing above this class.
    """

    name = "offline"

    def complete(
        self,
        messages: List[LLMMessage],
        *,
        max_tokens: int = 512,
        temperature: float = 0.4,
    ) -> LLMResponse:
        # Concatenate user-authored content; the offline engine keys off markers
        # that the prompt templates embed (e.g. "TASK: explain").
        user_text = "\n".join(m.content for m in messages if m.role == "user")
        system_text = "\n".join(m.content for m in messages if m.role == "system")

        answer = self._route(user_text, system_text)

        # Respect max_tokens loosely by trimming on a character budget (~4 chars
        # per token is a common rough approximation).
        char_budget = max_tokens * 4
        if len(answer) > char_budget:
            answer = answer[: char_budget - 1].rstrip() + "…"

        return LLMResponse(
            text=answer,
            provider=self.name,
            model="rule-engine-v1",
            is_live=False,
            meta={"note": "offline rule-based response; set AI_PROVIDER to use a live model"},
        )

    # -- internal routing ---------------------------------------------------

    def _route(self, user_text: str, system_text: str) -> str:
        """Pick a response strategy from structured markers in the prompt."""
        lowered = user_text.lower()

        task = self._extract(user_text, "TASK")
        if task:
            task = task.lower()

        if task == "explain" or "explain" in lowered:
            return self._explain(user_text)
        if task == "assess" or "assess" in lowered:
            return self._assess(user_text)
        # Generic fallback: echo a helpful, honest message.
        return (
            "This is an offline learning assistant. It can explain algorithms and "
            "give feedback on short answers, but a live model is not configured. "
            "Ask about a specific algorithm (e.g. Huffman, Dijkstra, LZ77) for a "
            "structured explanation."
        )

    def _explain(self, user_text: str) -> str:
        """Return a structured explanation for a named topic, if recognized."""
        topic = (self._extract(user_text, "TOPIC") or "").strip()
        level = (self._extract(user_text, "LEVEL") or "beginner").strip().lower()

        entry = _KNOWLEDGE_BASE.get(_normalize_topic(topic))
        if not entry:
            return (
                f"I don't have an offline explanation for '{topic or 'that topic'}'. "
                "Known topics include: "
                + ", ".join(sorted({v['title'] for v in _KNOWLEDGE_BASE.values()}))
                + ". Configure a live AI provider for open-ended questions."
            )

        depth = entry["deep"] if level in ("advanced", "expert") else entry["intro"]
        return (
            f"**{entry['title']}** — {entry['paradigm']}\n\n"
            f"{depth}\n\n"
            f"Complexity: {entry['complexity']}\n"
            f"Try it: {entry['try_it']}"
        )

    def _assess(self, user_text: str) -> str:
        """Give lightweight, keyword-overlap feedback on a learner's answer.

        This is a transparent heuristic (not grading intelligence): it compares
        the learner's answer against the expected key points for the topic and
        reports which concepts were covered. It exists so the /ai/assess contract
        is demonstrable offline; a live provider replaces it with real feedback.
        """
        topic = _normalize_topic((self._extract(user_text, "TOPIC") or "").strip())
        answer = (self._extract(user_text, "ANSWER") or "").strip()

        entry = _KNOWLEDGE_BASE.get(topic)
        if not entry:
            return (
                "Recorded your answer. Offline mode can't assess this topic; "
                "configure a live AI provider for detailed feedback."
            )

        keywords: List[str] = entry.get("keywords", [])
        answer_words = set(re.findall(r"[a-z0-9]+", answer.lower()))
        hit = [k for k in keywords if k.lower() in answer_words]
        missed = [k for k in keywords if k.lower() not in answer_words]

        score = round(100 * len(hit) / max(1, len(keywords)))
        lines = [f"Coverage score: {score}% ({len(hit)}/{len(keywords)} key concepts)."]
        if hit:
            lines.append("You mentioned: " + ", ".join(hit) + ".")
        if missed:
            lines.append("Consider also covering: " + ", ".join(missed) + ".")
        return "\n".join(lines)

    @staticmethod
    def _extract(text: str, marker: str) -> Optional[str]:
        """Pull a single-line ``MARKER: value`` field out of a prompt.

        The prompt templates in :mod:`ai.prompts` emit these markers so the
        offline engine can parse structured intent without an LLM.
        """
        match = re.search(rf"^{re.escape(marker)}:\s*(.+)$", text, re.MULTILINE)
        return match.group(1).strip() if match else None


# ---------------------------------------------------------------------------
# A minimal offline knowledge base
# ---------------------------------------------------------------------------
# Kept intentionally small and DAA-focused. It mirrors the tone of the existing
# frontend guide page so offline explanations feel consistent with the rest of
# the app. A live provider makes this obsolete for open-ended questions.

_KNOWLEDGE_BASE: Dict[str, Dict[str, object]] = {
    "huffman": {
        "title": "Huffman Coding",
        "paradigm": "Greedy",
        "intro": "Builds an optimal prefix code by repeatedly merging the two "
                 "least-frequent symbols into a binary tree. Frequent symbols end "
                 "up with shorter codes.",
        "deep": "Optimality follows from an exchange argument: any optimal prefix "
                "tree can be transformed to place the two rarest symbols as "
                "deepest siblings without increasing cost, which is exactly what "
                "the greedy merge produces.",
        "complexity": "O(N log K) time, O(K) space (K = distinct symbols).",
        "try_it": "Open the Huffman workspace and compress a low-diversity string.",
        "keywords": ["greedy", "prefix", "frequency", "tree", "optimal"],
    },
    "lz77": {
        "title": "LZ77",
        "paradigm": "Dictionary / sliding window",
        "intro": "Encodes data as (offset, length, next-char) triples that point "
                 "back to earlier matches inside a sliding window.",
        "deep": "A rolling hash over the window turns the naive O(N·W) match "
                "search into near-linear time, which is why real formats like "
                "GZIP build on LZ77.",
        "complexity": "O(N) optimized / O(N·W) naive; O(W) window space.",
        "try_it": "Open the LZ77 inspector and watch the window slide over "
                  "repeated substrings.",
        "keywords": ["window", "offset", "length", "dictionary", "match"],
    },
    "dijkstra": {
        "title": "Dijkstra's Shortest Path",
        "paradigm": "Greedy",
        "intro": "Grows a set of finalized vertices, always finalizing the "
                 "nearest unvisited vertex and relaxing its outgoing edges.",
        "deep": "Correctness relies on non-negative weights: once a vertex is "
                "popped from the min-heap its distance is final, because no later "
                "path through unvisited (farther) vertices can be shorter.",
        "complexity": "O((V + E) log V) with a binary heap.",
        "try_it": "Open the network-routing page and route between two nodes.",
        "keywords": ["greedy", "relaxation", "heap", "nonnegative", "shortest"],
    },
    "mergesort": {
        "title": "Merge Sort",
        "paradigm": "Divide & Conquer",
        "intro": "Recursively splits the array in half, sorts each half, then "
                 "merges the two sorted halves in linear time.",
        "deep": "The recurrence T(N) = 2T(N/2) + O(N) solves to O(N log N) by the "
                "master theorem; stability comes from breaking merge ties toward "
                "the left half.",
        "complexity": "O(N log N) time (all cases), O(N) auxiliary space.",
        "try_it": "Open the sorting lab and step through the merge frames.",
        "keywords": ["divide", "conquer", "merge", "recursion", "stable"],
    },
}


def _normalize_topic(topic: str) -> str:
    """Map a free-text topic to a knowledge-base key (e.g. 'Merge Sort' -> 'mergesort')."""
    return re.sub(r"[^a-z0-9]", "", topic.lower())


# ---------------------------------------------------------------------------
# Provider registry + factory (the one place the process picks a provider)
# ---------------------------------------------------------------------------

# Maps the AI_PROVIDER env value to a provider class. New providers register here
# and become selectable by env var alone — no other code changes.
_PROVIDER_REGISTRY: Dict[str, Type[LLMProvider]] = {
    "offline": OfflineProvider,
    # Future, e.g.:
    #   "claude": ClaudeProvider,
    #   "openai": OpenAIProvider,
    #   "gemini": GeminiProvider,
    #   "local":  LocalLLMProvider,
}


def register_provider(key: str, provider_cls: Type[LLMProvider]) -> None:
    """Register a provider implementation under ``key``.

    Exposed so a real provider can be added from a separate module (or a plugin)
    without editing this file. Call this at import time, before the first
    :func:`get_provider` call.
    """
    _PROVIDER_REGISTRY[key.lower()] = provider_cls


@lru_cache(maxsize=1)
def get_provider() -> LLMProvider:
    """Return the process-wide provider selected by the ``AI_PROVIDER`` env var.

    Resolution order:
    1. Read ``AI_PROVIDER`` (default ``"offline"``).
    2. Look it up in :data:`_PROVIDER_REGISTRY`; unknown keys fall back to offline.
    3. If the chosen provider reports it is not available (e.g. a missing API
       key), fall back to the offline provider so requests never hard-fail.

    Cached so the provider is constructed once per process.
    """
    key = os.environ.get("AI_PROVIDER", "offline").strip().lower()
    provider_cls = _PROVIDER_REGISTRY.get(key, OfflineProvider)

    provider = provider_cls()
    if not provider.is_available():
        # Graceful degradation: configured provider can't serve (missing key,
        # SDK not installed, ...). Offline keeps the platform fully usable.
        return OfflineProvider()
    return provider


def describe_provider() -> Dict[str, object]:
    """Return a small, JSON-serializable summary of the active provider.

    Used by the ``GET /ai/health`` endpoint so the frontend can display whether
    a live model is wired up.
    """
    provider = get_provider()
    return {
        "provider": provider.name,
        "is_live": provider.name != "offline",
        "registered": sorted(_PROVIDER_REGISTRY.keys()),
    }
